### ISSUE TITLE
咨询一下 ，socket 如何同时支持多客户端连接访问？

### ISSUE THREAD

**Issue by songyongzhan** [farwish/PCP#2]
请问一下老师，socket如何同时支持多客户端访问？

另外多客户端访问后，如何支持长连接？  

请老师帮忙

574482856@qq.com

**Comment by farwish** [comment]
@songyongzhan 可以使用多进程或者多路复用实现，多路复用在31节讲到；只要服务端不断开、不关闭客户端，就是长连接了。

**Comment by songyongzhan** [comment]
> @songyongzhan 可以使用多进程或者多路复用实现，多路复用在31节讲到；只要服务端不断开、不关闭客户端，就是长连接了。


恩，如果我需要同时支持10个人在线，那么我的程序中必须要启动10个进程，是这样的吗？

还是好期待老师在课程中，说一说的，呵呵。

期待后面的教程。

**Comment by songyongzhan** [comment]
恩，如果我需要同时支持10个人在线，那么我的程序中必须要启动10个进程，是这样的吗？

还是好期待老师在课程中，说一说的，呵呵。

期待后面的教程

**Comment by farwish** [comment]
@songyongzhan 复用的话就不需要10个进程了。
