### ISSUE TITLE
尔康老师，能不能做一个 商品 秒杀的高并发 实战呢？

### ISSUE THREAD

**Issue by Phantoms007** [farwish/PCP#4]
网上很多教程是结合redis 实现高并发下的商品秒杀，褒贬不一，尔康老师有么有这样的案例呢？

**Comment by farwish** [comment]
@Phantoms007  如果后面有机会的话。案例一般是关注在局部实现以及原理，真实的业务场景往往更复杂，要考虑多种可能，应根据当前系统的情况来分析。
